"""add_catalog_versions_table

Revision ID: 009_add_catalog_versions_table
Revises: 008_rename_started_at_to_created_at
Create Date: 2025-01-28 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '009_add_catalog_versions_table'
down_revision = '008_rename_started_at'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Таблица catalog_versions уже существует, добавляем новые поля
    
    # Добавляем новые колонки
    op.add_column('catalog_versions', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('catalog_versions', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('catalog_versions', sa.Column('progress_message', sa.String(length=500), nullable=True))
    op.add_column('catalog_versions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('catalog_versions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    
    # Изменяем существующие колонки
    op.alter_column('catalog_versions', 'filename', type_=sa.String(length=255))
    op.alter_column('catalog_versions', 'file_size', type_=sa.BigInteger())
    op.alter_column('catalog_versions', 'products_count', type_=sa.Integer(), nullable=True)
    
    # Обновляем constraint для статуса
    op.drop_constraint('check_catalog_status', 'catalog_versions', type_='check')
    op.create_check_constraint('check_catalog_version_status', 'catalog_versions', 
                              "status IN ('uploaded', 'processing', 'completed', 'failed', 'active')")
    
    # Добавляем новый constraint для прогресса
    op.create_check_constraint('check_catalog_version_progress', 'catalog_versions', 
                              'progress >= 0 AND progress <= 100')
    
    # Обновляем индексы
    op.drop_index('idx_catalog_versions_status_created', table_name='catalog_versions')
    op.create_index('idx_catalog_versions_active', 'catalog_versions', ['status', 'created_at'], unique=False)
    op.create_index('idx_catalog_versions_created', 'catalog_versions', ['created_at'], unique=False)
    op.create_index('idx_catalog_versions_status', 'catalog_versions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_catalog_versions_status', table_name='catalog_versions')
    op.drop_index('idx_catalog_versions_created', table_name='catalog_versions')
    op.drop_index('idx_catalog_versions_active', table_name='catalog_versions')
    op.drop_table('catalog_versions')
    # ### end Alembic commands ###
