"""Add usage_statistics table for AI cost tracking

Revision ID: 8bd76168eb7e
Revises: 009_add_catalog_versions_table
Create Date: 2025-09-28 13:59:58.126906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd76168eb7e'
down_revision = '009_add_catalog_versions_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('admin_users_email_key'), 'admin_users', type_='unique')
    op.drop_constraint(op.f('admin_users_username_key'), 'admin_users', type_='unique')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_index('idx_catalog_versions_status_created', 'catalog_versions', ['status', 'created_at'], unique=False)
    op.drop_column('company_services', 'title')
    op.drop_column('company_services', 'active')
    op.drop_column('company_services', 'category')
    op.alter_column('conversations', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('conversations', 'platform',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_conversations_chat_id'), table_name='conversations')
    op.alter_column('leads', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('leads', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('leads', 'company',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('leads', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('leads', 'sync_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('leads', 'zoho_lead_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('leads', 'auto_created',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('leads', 'lead_source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=True)
    op.drop_index(op.f('idx_leads_status_created'), table_name='leads')
    op.add_column('messages', sa.Column('message_type', sa.String(length=20), nullable=False))
    op.add_column('messages', sa.Column('processing_time_ms', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('llm_provider', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.drop_column('messages', 'extra_data')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('idx_logs_level_created'), table_name='system_logs')
    op.create_index('idx_logs_level_created', 'system_logs', ['level', 'created_at'], unique=False)
    op.create_index('idx_logs_created', 'system_logs', ['created_at'], unique=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index('idx_logs_created', table_name='system_logs')
    op.drop_index('idx_logs_level_created', table_name='system_logs')
    op.create_index(op.f('idx_logs_level_created'), 'system_logs', ['level', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.add_column('messages', sa.Column('extra_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'tokens_used')
    op.drop_column('messages', 'llm_provider')
    op.drop_column('messages', 'processing_time_ms')
    op.drop_column('messages', 'message_type')
    op.create_index(op.f('idx_leads_status_created'), 'leads', ['status', 'created_at'], unique=False)
    op.alter_column('leads', 'lead_source',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('leads', 'auto_created',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('leads', 'zoho_lead_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('leads', 'sync_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('leads', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('leads', 'company',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('leads', 'phone',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('leads', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('leads', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_conversations_chat_id'), 'conversations', ['chat_id'], unique=False)
    op.alter_column('conversations', 'platform',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('conversations', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('conversations', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.add_column('company_services', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('company_services', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('company_services', sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_index('idx_catalog_versions_status_created', table_name='catalog_versions')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=False)
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('admin_users_username_key'), 'admin_users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('admin_users_email_key'), 'admin_users', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
